### ISSUE TITLE
反馈一个BUG，10.21更新的脚本，在删除已完成任务时会删除下载文件夹下的所有文件

### ISSUE THREAD

**Issue by SuperNG6** [P3TERX/aria2.conf#11]
具体表现为，添加下载任务时，手动多添加一个子文件夹，删除已完成任务时就会删除这个子文件夹，也就是说所有下载到该子文件夹下的任务所下载的文件都会被被删除

![](https://github.com/SuperNG6/pic/blob/master/issues/Pasted%20Graphic.png)

**Comment by P3TERX** [comment]
1. 删除已完成任务并不会触发脚本，没有这个功能，文件不可能被删除。
2. 如果“手动多添加一个子文件夹”是指自定义下载路径那么问题应该在这里，Aria2 设置的下载路径必须与脚本中的下载路径一致，否则在下载完成时会因路径错误而导致文件被误删。

**Comment by SuperNG6** [comment]
可是却是有这个问题，之前的脚本没有这个问题
例：conf文件中设置的下载路径为 ``/downloads``，添加下载任务时在AriaNG中多添加一级子目录``/downloads/video``，这时删除掉已完成的任务，则会把这个子目录``/downloads/video``下所有文件全部删除

**Comment by P3TERX** [comment]
你这个操作就是修改了下载路径，前面我说了**路径必须一致**，因为脚本是基于下载路径去做转换和判断的，你瞎改它就会瞎搞。之前的脚本只不过是没删文件而已，你以同样的方式使用也可能会遇到其他问题。
