### ISSUE TITLE
关于BT下载完后上传问题

### ISSUE THREAD

**Issue by fatsaltyfish** [P3TERX/aria2.conf#13]
BT下载完成后还需要**等待做种完成**才会开始上传。
ondownload-complete 和 on-bt-download-complete的区别如下:
![image](https://user-images.githubusercontent.com/53555543/73462163-4d682080-43b6-11ea-823a-9952b62ca68c.png)
需要在下载完后**即刻**开始上传文件并且**不会重复上传**。
congig里加上 on-bt-download-complete=
以下为本人自改脚本（**水平有限仅供参考**）:
#!/bin/bash

GID="$1";
FileNum="$2";
File="$3";
MinSize="5"  #5K
MaxSize="157286400"  #15G
RemoteDIR="/root/ftppanshi/";  #rclone path
LocalDIR="/home/wwwroot/default/Download/";  #Aria2 Dowanload Path
log_file="/etc/aria2/upload.log";

echo "`date +'%Y-%m-%d %H:%M:%S'`:  $output" >> $log_file;
echo $GID>> $log_file;
echo $FileNum>> $log_file;
echo $File>> $log_file;

if [[ -z $(echo "$FileNum" |grep -o '[0-9]*' |head -n1) ]]; then FileNum='0'; fi
if [[ "$FileNum" -le '0' ]]; then exit 0; fi
if [[ "$#" != '3' ]]; then exit 0; fi

function LoadFile(){
  IFS_BAK=$IFS
  IFS=$'\n'
  if [[ ! -d "$LocalDIR" ]]; then return; fi
  if [[ -e "$File" ]]; then
    FileLoad="${File/#$LocalDIR}"
 
	echo $FileLoad;
   
        if [[ "$FileLoad" == '/' ]]; then echo "end"; return; fi
	
        
	
	
	fl="${FileLoad#*/}";
	echo $fl;

        FileLoad=$(basename "$FileLoad");
	echo $FileLoad;
	if [[ "$fl" != "$FileLoad" ]]; then 
	FileLoad=$fl; 
	FileLoad=$(dirname "$FileLoad");
	tmplog_file="/etc/aria2/"$FileLoad".log";
	else
	tmplog_file="/etc/aria2/"$FileLoad".log";
	echo "single file">$tmplog_file;
	fi
	echo $FileLoad;
	
	echo $tmplog_file;
	
      if [ ! -e $tmplog_file ];then
	 
	 echo "on-bt-download-complete">$tmplog_file;
      else 
	 state=$(cat $tmplog_file | sed -n 1p) ;

	#echo $state;
	if [ $state == "on-bt-download-complete" ]; then 
	echo "on-download-complete">$tmplog_file;  
	exit;
	elif [ $state == "single file" ];then
	echo "single file";
	else
	rm -rf $tmplog_file;
	exit;
	fi

      fi

    if [[ "$FileLoad" == "$LocalDIR" ]]; then return; fi
    EXEC="$(command -v cp)"
    if [[ -z "$EXEC" ]]; then return; fi
    Option=" -f -r";
    cd "$LocalDIR";
    if [[ -e "$FileLoad" ]]; then
	
      ItemSize=$(du -s "$FileLoad" |cut -f1 |grep -o '[0-9]*' |head -n1)
	
	echo $ItemSize;
      if [[ -z "$ItemSize" ]]; then return; fi
      if [[ "$ItemSize" -le "$MinSize" ]]; then
        echo -ne "\033[33m$FileLoad \033[0mtoo small to spik.\n";
        return;
      fi
      if [[ "$ItemSize" -ge "$MaxSize" ]]; then
        echo -ne "\033[33m$FileLoad \033[0mtoo large to spik.\n";
        return;
      fi

	
	
	
	
	while true
	do
	ls $RemoteDIR;
	if [ $? -eq 0 ]; then break;
	fi
	done
	

	
	
	if [  -f "${RemoteDIR}$FileLoad" ]; then
	echo "exist file!";
	exit;
	fi
	

	if [  -d "${RemoteDIR}$FileLoad" ]; then
  	echo "exist directory!";
	exit;
	fi
	
	
	while true
	do
	cd "$LocalDIR";
      	eval "${EXEC}${Option}" \'"${FileLoad}"\' "${RemoteDIR}";
	if [ $? -eq 0 ]; then 
	state=$(cat $tmplog_file | sed -n 1p) ;
	if [ $state == "on-bt-download-complete" ]; then 
	echo "on-upload-complete">$tmplog_file;  
	else
	rm -rf $tmplog_file;
	fi
	break;
	fi
	
	done
    fi
  fi
  IFS=$IFS_BAK
}
LoadFile;

**Comment by P3TERX** [comment]
在不考虑下载完成后持续做种的情况下把做种时间设为0即可，下载完会直接开始上传。

**Comment by fatsaltyfish** [comment]
下载完不做种不利于资源的分享。一般来说分享率设置为1的情况下下载完还需要做种一段时间还会结束。希望能够在做种的情况下一下载完成就上传。

**Comment by P3TERX** [comment]
首先非常感谢您的建议，实际上最初我有尝试过，但有以下的一些问题：
1. 同时做种并同时上传会导致上行带宽被大量占用，此时做种效果并不好。
2. 上传完成文件被删除（`rclone move`）的情况，可能就几分钟甚至几秒，做种时间成为摆设。
3. 强行让他人持续做种会导致“为什么下载卡在了100%？”之类的傻逼问题出现，并不是所有人都知道什么叫做种。

然后你要了解做种时间设置为0下载完不会继续做种，它并不受分享率控制，参见[官方文档](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-seed-time)。
![image](https://user-images.githubusercontent.com/25927179/73515300-c6578e80-442f-11ea-980a-518c760e8818.png)

关于资源分享，实际上下载的同时也在做种，并不会有不利于分享的情况。下载完后上传也是为了更好的分享，上传到网盘了资源就相当于永久化了，如今通过 Google Drive 做资源分享的人大多都受益于此项目。

所以想要高质量的持续做种和分享，自由控制设置做种时间做种完再上传才是更好的选择。

**Comment by fatsaltyfish** [comment]
1.同时上传和做种会影响两方速度，但大多情况是，下载完后，没人请求资源，种子挂着的时候可以进行上传。
2.我这边是在bt种子下载完成后先copy，做种完成之后再删除。
3.实际上上传到onedrive的速度很快完爆做种的上传速度，但是做种时间却相对较长，有时候想要下载完立刻上传到onedrive后在线播放的话就得等待做种时间了。
4.其实提出这个问题是希望能够更好地兼顾做种和上传。个人认为等待做种完再上传是一种不必要的等待。

**Comment by P3TERX** [comment]
本来是打算等有空了进行整合优化的，但这段时间我的博客收到非常的多的留言是“如何关闭 Aria2 上传”，想了想还是算了。

**Comment by fatsaltyfish** [comment]
好吧，大部分人还是只关注自己的下载进度的。
