### ISSUE TITLE
强制加密或许无法防迅雷

### ISSUE THREAD

**Issue by snylonue** [P3TERX/aria2.conf#14]
启用`bt-require-crypto=true`和`bt-min-crypto-level=arc4`后仍会向迅雷上传

[另见](https://bgm.tv/group/topic/353777#post_1535757)

**Comment by P3TERX** [comment]
![](https://user-images.githubusercontent.com/25927179/74611344-d496f180-5135-11ea-8800-97a2ed343ddc.png)
我自己的实际体验是并没有给迅雷任何上传，而且迅雷很快会被踢掉。

**Comment by snylonue** [comment]
![Snipaste_2020-02-17_16-27-32](https://user-images.githubusercontent.com/48825598/74636179-6fc5b080-51a2-11ea-8a14-43d395638e8e.png)
又测试了一下

**Comment by P3TERX** [comment]
只要不给迅雷上传，防吸血的目的就达到了，这点你要明白。

**Comment by snylonue** [comment]
但是给迅雷上传了

**Comment by P3TERX** [comment]
抱歉，才看到有图片。但我并没遇到给迅雷上传的情况，确定你的配置生效了？

**Comment by snylonue** [comment]
确定，修改配置文件后aria2重启过

**Comment by WhiteSnowPinkPinkWhatItLike** [comment]
发现同样问题：
![迅雷](https://cdn.17shou.vip/2020/03/25/6210415445656.png)
* Centos 7.3

**Comment by P3TERX** [comment]
差不多两个月了，我自己至今一个都没遇到，这就很诡异了。相关文案已经修改，继续观察...

**Comment by Snowflake-Pink** [comment]
> 差不多两个月了，我自己至今一个都没遇到，这就很诡异了。相关文案已经修改，继续观察...

您是大陆的服务器吗？
我是香港的，会不会和这个有关QwQ

**Comment by snylonue** [comment]
@Snowflake-Pink 我是大陆的
