### ISSUE TITLE
如何设置开启HTTPS下载

### ISSUE THREAD

**Issue by cmdegr** [P3TERX/aria2.conf#15]
HTTPS无法下载.
我想下载一个IDEA:  https://download-cf.jetbrains.com/idea/ideaIU-2019.3.3.exe
无法下载

**Comment by cmdegr** [comment]
我用的是 <<Aria2 一键安装管理脚本>>, 安装的aria2.
可以进行bt下载.

**Comment by P3TERX** [comment]
不需要设置，直接可以下载，除非 CA 证书没有被正确安装。你可以尝试执行``

**Comment by cmdegr** [comment]
不行, 还是不能下载https, 我的系统是Ubuntu16.04

root@SSRVPS:~# aria2c https://download-cf.jetbrains.com/idea/ideaIU-2019.3.3.exe

02/23 14:56:32 [NOTICE] Downloading 1 item(s)

02/23 14:56:32 [ERROR] IPv4 RPC: failed to bind TCP port 6800
Exception: [SocketCore.cc:312] errorCode=1 Failed to bind a socket, cause: Address already in use

02/23 14:56:32 [ERROR] Exception caught
Exception: [DownloadEngineFactory.cc:219] errorCode=1 Failed to setup RPC server.

**Comment by cmdegr** [comment]
我尝试杀掉占用6800 的线程, 然后手动用命令行下载HTTPS,  还是不行.

**Comment by P3TERX** [comment]
重启、重装
