### ISSUE TITLE
建议增加下载完成或删除任务后自动删除.torrent文件的脚本

### ISSUE THREAD

**Issue by wowaqly** [P3TERX/aria2.conf#18]
建议增加下载完成或删除任务后自动删除.torrent文件的脚本，这样就比较接近完美的体验了，否则每次还要手动删除

**Comment by he-sb** [comment]
附议 :see_no_evil

**Comment by P3TERX** [comment]
这个之前就有想过，有几种方案：
1. 通过修改配置文件如下选项可以不保留种子文件。但这样做会带来副作用，重启后正在下载的任务会丢失，因为重新加载任务需要读取种子文件，种子文件不存在任务也就没有了。
```
# 保存磁力链接元数据为种子文件(.torrent文件), 默认:false
bt-save-metadata=false
# 保存上传的种子，默认:true
rpc-save-upload-metadata=false
```

2. 删除指定种子文件，无法获取种子文件的路径，无法实现。
3. 删除所有种子文件，会影响正在下载和等待下载的任务，弃坑。
