### ISSUE TITLE
tracker.sh运行时无法找到同目录下的aria2.conf

### ISSUE THREAD

**Issue by lujimmy** [P3TERX/aria2.conf#19]
操作系统：macOS Catalina 10.15.4 Beta版(19E242d)

**Comment by P3TERX** [comment]
![image](https://user-images.githubusercontent.com/25927179/76050606-f94af000-5fa2-11ea-8169-32daa48d8508.png)

macOS 自己想办法装 GNU 命令行工具应该能用
