### ISSUE TITLE
Aria2 启动失败 

### ISSUE THREAD

**Issue by CKH0** [P3TERX/aria2.conf#21]
Parse error in /root/.aria2/aria2.conf
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--rpc-certificate'.
  -> [OptionHandlerImpl.cc:556] errorCode=1 Could not get file status: No such file or directory
Usage:
 --rpc-certificate=FILE       Use the certificate in FILE for RPC server.
                              The certificate must be in PEM format.
                              Use --rpc-private-key option to specify the
                              private key. Use --rpc-secure option to enable
                              encryption.

**Comment by P3TERX** [comment]
注释`rpc-certificate`和`rpc-private-key`这两个选项，我刚刚不小心推了一个没注释的配置文件。
