### ISSUE TITLE
建议完成任务脚本添加完成任务后将文件放置在另一个文件夹里面，

### ISSUE THREAD

**Issue by shanzhaozhen** [P3TERX/aria2.conf#22]
建议完成任务脚本添加完成任务后将文件放置在另一个文件夹里面，类似transmission那样子操作，毕竟用到nas，任务的下载量会比较大，在任务文件夹找文件会比较麻烦，同时这样子配合filebrower，下完片就直接看效果也很好

**Comment by P3TERX** [comment]
感谢建议，相关功能的脚本现在已经添加。
