### ISSUE TITLE
建议上传日志单独归档

### ISSUE THREAD

**Issue by cgkings** [P3TERX/aria2.conf#24]
大佬，你好，首先感谢你的脚本，帮助小白用上离线下载！
目前，脚本中上传和下载信息在一个日志里面，查找起来很不方便，其实我们打开日志就是想看上传日志，下载信息在ariang面板里都有不需要打开日志，所以建议能不能上传日志单独归档，这样看起来比较方便，上传进度和是否完成上传也好查！

**Comment by P3TERX** [comment]
加了单独保存上传信息日志功能，只保存成功和失败的简单信息，可以在脚本中手动选择开启。
如果你觉得 Aria2 的日志对你来说没必要可以通过修改配置文件开启安静模式。

**Comment by cgkings** [comment]
> 加了单独保存上传信息日志功能，只保存成功和失败的简单信息，可以在脚本中手动选择开启。
> 如果您觉得Aria2的日志对您来说没必要可以通过修改配置文件开启安静模式。
在哪个版本加了单独保存上传信息日志功能，我改怎么更新它，另外，有cat命令查看完整日志，那有没有cat命令查看单独的上传是指呢？
