### ISSUE TITLE
文件移动脚本(move.sh) 能增加文件大小类型过滤吗？

### ISSUE THREAD

**Issue by hyperlook** [P3TERX/aria2.conf#25]
文件移动脚本(move.sh) 能增加文件大小类型过滤吗？用plex等媒体库的应该都有这需求，感谢！

**Comment by P3TERX** [comment]
本来是打算加的，上传脚本中都有类似的功能，但实际上像一些小文件基本都下不动，会卡任务，一般下载时都手动去掉了，所以加上实际意义也不大了。
