### ISSUE TITLE
手动指定下载路径时.aria2 文件删除失败问题(已找到原因，望修复)

### ISSUE THREAD

**Issue by zwc456baby** [P3TERX/aria2.conf#27]
## 触发条件

直接上结论：

如果 **手动指定** 下载路径且下载的 BT 是 **包含多个文件** 的文件夹，此时无法正确删除自动生成的 .aria2 文件。

对于一般小白用户，如果添加 bt 时，没有手动指定路径，或者下载的 bt 只有一个文件。目前的脚本都可以正常删除 .aria2

## 例子

> 就以我目前的配置和实际情况来讲解了

在 `aria2.conf` 配置中,我设定默认下载目录为 ： `dir=/media/pi/hdd/downloads`

在 `delete.aria2.sh` 脚本中，我同样设定目录为： `DOWNLOAD_PATH='/media/pi/hdd/downloads'`

#### 默认情况下

> 添加Bt 种子 -》 复制 bt 到输入框 -》 点击下载
> 没有手动输入下载路径的情况下

此时我要下载一个 bt 种子，假设这个 bt 种子含有多个文件，下载后便是一个文件夹，假设下载后目录结构和文件是这样的：

```
/media/pi/hdd/downloads/文件夹/文件1
/media/pi/hdd/downloads/文件夹/文件2
/media/pi/hdd/downloads/文件夹.aria2
```

在 `delete.aria2.sh` 脚本中，有这么一行 `TOP_PATH=${DOWNLOAD_PATH}/${REMOVE_DOWNLOAD_PATH%%/*}`

这时候的脚本会正确拼接成路径 `/media/pi/hdd/downloads/文件夹` ，然后成功删除 `.aria2` 文件

#### 手动指定下载路径

> 添加Bt 种子 -》 复制 bt 到输入框 -》 设定下载目录 -》 点击下载

假设我这次设定的目录是： `/media/pi/hdd/downloads/test1/test2` 

此时下载同一个 bt 种子，下载后目录结构和文件是这样的：

```
/media/pi/hdd/downloads/test1/test2/文件夹/文件1
/media/pi/hdd/downloads/test1/test2/文件夹/文件2
/media/pi/hdd/downloads/test1/test2/文件夹.aria2
```

那么  `delete.aria2.sh` 脚本中的 `TOP_PATH=${DOWNLOAD_PATH}/${REMOVE_DOWNLOAD_PATH%%/*}` 行，拼接后的路径为：

```
/media/pi/hdd/downloads/test1
```

此时尝试删除 `/media/pi/hdd/downloads/test1.aria2` 文件显然是不对的

原因就是这种方式只能获取一级目录，而我设定的目录包含了两个子目录 `test1` 和 `test2`

将这一行脚本修改为： `TOP_PATH=${DOWNLOAD_PATH}/$(dirname $REMOVE_DOWNLOAD_PATH)`

使用 `dirname` 获取到两个子目录，此时拼接的路径为：

```
/media/pi/hdd/downloads/test1/test/文件夹
```

然后就能正确删除了。

> 我只使用了 `delete.aria2.sh` 脚本，如果其他脚本中也是这样的获取方式，应该有同样的问题

#### 附上我目前的脚本，供参考

```
#!/usr/bin/env bash

DOWNLOAD_PATH='/media/pi/hdd/downloads'

if [ ! -d $DOWNLOAD_PATH ]; then
    echo 'path not exists'
    exit 1
fi

FILE_PATH=$3
REMOVE_DOWNLOAD_PATH=${FILE_PATH#${DOWNLOAD_PATH}/}
# TOP_PATH=${DOWNLOAD_PATH}/${REMOVE_DOWNLOAD_PATH%%/*}
TOP_PATH=${DOWNLOAD_PATH}/$(dirname $REMOVE_DOWNLOAD_PATH)
# echo log
LIGHT_GREEN_FONT_PREFIX="\033[1;32m"
FONT_COLOR_SUFFIX="\033[0m"
INFO="[${LIGHT_GREEN_FONT_PREFIX}INFO${FONT_COLOR_SUFFIX}]"

echo -e "$(date +"%m/%d %H:%M:%S") ${INFO} Delete .aria2 file ..."

if [ "$2"x == "0"x ]; then
    echo 'file length is zero'
    exit 0
elif [ -f "${FILE_PATH}.aria2" ]; then
    rm -vf "${FILE_PATH}.aria2"
elif [ -f "${TOP_PATH}.aria2" ]; then
    rm -vf "${TOP_PATH}.aria2"
fi

```

**Comment by P3TERX** [comment]
你所提供的这个修改方案和最初的方案有点类似，实现方法不同，目的都是去掉文件名那一个层级。最初觉得已经相当完美了，但 BT 下载有一种情况是多层级文件夹。

假设和你一样在 Aria2 下载时修改路径，那么所下载的文件目录结构会是以下这样：
```
downloads
└── test1
    └── test2
        ├── 文件夹
        │   ├── 文件1
        │   ├── 文件2
        │   └── 文件夹2
        │       ├── 文件3
        │       └── 文件4
        └── 文件夹.aria2
```
这种情况 Aria2 给脚本所传递的路径为：`./downloads/test1/test2/文件夹/文件夹2/文件3`

假设只去掉文件名那一个层级，那么`.aria2`文件会判断为：`./downloads/test1/test2/文件夹/文件夹2.aria2`

与实际的`./downloads/test1/test2/文件夹.aria2`不符，`.aria2`文件没有被删除，这种情况只去掉文件名一个层级显然是不行的。

正是因为这种情况的存在，所以目前所有脚本都是 BT 下载文件夹时取顶层目录，不管是一个层级和多个层级都适用，但前提是 Aria2 与脚本的下载目录必须一致。对于下载时修改目录我个人没有需求，也很少有人提及，所以就没有继续挖坑研究了。

你是我见过的把问题写得最详细、思路最清晰的，要是都能像你这样很多问题都非常好解决了。欢迎继续提供一些建议和想法。

**Comment by zwc456baby** [comment]
由于 aria2 不会传递更多参数，而第三个参数可能传递成子目录的路径

是否可以对传递过来的路径，向上递归目录进行查找删除

例如设定默认下载目录 `/media/pi/downloads`
下载的时候设定成了子目录： `/media/pi/downloads/test1/test2/test3`

下载之后传过来的参数是： `/media/pi/downloads/test1/test2/test3/文件夹1/文件夹2/文件3`

则查找
`/media/pi/downloads/test1/test2/test3/文件夹1/文件夹2/文件3.aria2`

找不到则：
`/media/pi/downloads/test1/test2/test3/文件夹1/文件夹2.aria2`
`/media/pi/downloads/test1/test2/test3/文件夹1.aria2`
`/media/pi/downloads/test1/test2/test3.aria2`

一直递归直到：
`/media/pi/downloads/test1.aria2’

---

当然这是限定了查找目录为设定的默认下载目录 `DOWNLOAD_PATH`
不会查找到 `/media.aria2`
如果设定的目录是 `/media/pi/downloads`
下载时手动指定了下载目录为： `/tmp/downloads`
则不会成功递归找到 `.aria2` 文件

> (这种设定方式一般不会出现，即便是设定目录，一般也是默认目录的子目录。而我的设备有多个盘符，某些文件我要下载到其它盘符去，所以对于我有这种需求。作者其实可以忽略)

也可以不限定递归目录，则会一直递归，直到根目录 `/tmp.aria2`
> 我觉得递归到根目录这种方式很不好，所以我自己也没有使用

---

限定递归目录的情况下，脚本文件中的两个 `if` 判断足够应付大多数情况了。
下面是我修改后自用的脚本：


```
#!/usr/bin/env bash

log -faria2delete.log 'delete aria2 from download file:' $@

DOWNLOAD_PATH='/media/pi/hdd/downloads'
FILE_PATH=$3

if [ ! -d $DOWNLOAD_PATH ]; then
    echo 'path not exists'
    exit 1
fi
if [ "$FILE_PATH"x == ""x ]; then
    echo '$3 path not exists'
    exit 1
fi

PARENT_PATH=$(dirname $FILE_PATH)
REMOVE_DOWNLOAD_PATH=${FILE_PATH#${DOWNLOAD_PATH}/}
#TOP_PATH=${DOWNLOAD_PATH}/${REMOVE_DOWNLOAD_PATH%%/*}
# TOP_PATH=${DOWNLOAD_PATH}/$(dirname $REMOVE_DOWNLOAD_PATH)
LIGHT_GREEN_FONT_PREFIX="\033[1;32m"
FONT_COLOR_SUFFIX="\033[0m"
INFO="[${LIGHT_GREEN_FONT_PREFIX}INFO${FONT_COLOR_SUFFIX}]"

echo -e "$(date +"%m/%d %H:%M:%S") ${INFO} Delete .aria2 file ..."

function findParentDirAria2 () {
    if [ "$TOP_PATH"x == "$DOWNLOAD_PATH"x -o "$TOP_PATH"x == "/"x ]; then
        log -faria2delete.log 'can not delete file .aria2:' $FILE_PATH
        return
    fi
    # 执行文件检测
    echo "$TOP_PATH"
    if [ -f "${TOP_PATH}.aria2" ]; then
        log -faria2delete.log 'success delete file .aria2:' $TOP_PATH
        rm -vf "${TOP_PATH}.aria2"
        return
    fi

    # 末尾递归调用本方法
    TOP_PATH=$(dirname $TOP_PATH)
    findParentDirAria2
}

if [ "$2"x == "0"x ]; then
    echo 'file length is zero'
    exit 0
elif [ -f "${FILE_PATH}.aria2" ]; then
    log -faria2delete.log 'success delete file .aria2:' $FILE_PATH
    rm -vf "${FILE_PATH}.aria2"
# 查找父目录的 .aria2文件，只查找一级
# 因为限制了递归目录为默认目录，所以查找一层父目录
# 为了兼容手动设定的下载目录与默认下载目录不同的情况
elif [ -f "${PARENT_PATH}.aria2" ]; then
    log -faria2delete.log 'success delete file .aria2:' $PARENT_PATH
    rm -vf "${PARENT_PATH}.aria2"
#elif [ -f "${TOP_PATH}.aria2" ]; then
#    log -faria2delete.log 'success delete file .aria2:' $TOP_PATH
#    rm -vf "${TOP_PATH}.aria2"
else
    # 向上递归查找路径下的 .aria2 文件
    # 为了避免递归到 / 根目录，只在 DOWNLOAD_PATH 目录中进行递归查找
    # 如果不限定递归目录，则将 TOP_PATH 目录修改为下列样式:
    #TOP_PATH=$FILE_PATH
    TOP_PATH=${DOWNLOAD_PATH}/$(dirname $REMOVE_DOWNLOAD_PATH)
    findParentDirAria2
fi

```
