### ISSUE TITLE
autoupload.sh怎么设置多用户上传GD，750G限制不够用

### ISSUE THREAD

**Issue by cgkings** [P3TERX/aria2.conf#28]
如题，对于rclone上传到googledrive有流量限制，单用户750G，对于下载量来说不够用，请问有什么办法可以到流量限制，自动切换用户继续上传吗？就像gclone一样

**Comment by he-sb** [comment]
自己改一下 rclone 上传的脚本，把里面的 rclone 替换成 gclone 就可以了。

**Comment by cgkings** [comment]
> 自己改一下rclone上传的脚本，把里面的rclone替换成gclone就可以了。

那账号需要换吗？因为gclone没有token，我专门用rclone又新建了一个账号
因为rclone只需要个token，其他都没填，是吧gclone账号里的除token以外的信息复制到rclone账号就行了吧，这样就可以用accounts文件夹里的sa了吧

**Comment by he-sb** [comment]
> > 自己改一下rclone上传的脚本，把里面的rclone替换成gclone就可以了。
> 
> 那账号需要换吗？因为gclone没有token，我专门用rclone又新建了一个账号
> 因为rclone只需要个token，其他都没填，是吧gclone账号里的除token以外的信息复制到rclone账号就行了吧，这样就可以用accounts文件夹里的sa了吧
> 
> 
> 
> 

gclone 会用的话类比一下就行了啊
