### ISSUE TITLE
下载错误重试的命令应该怎么写？

### ISSUE THREAD

**Issue by oracle91** [P3TERX/aria2.conf#31]
下载错误后执行的命令，此项未定义则执行下载停止后执行的命令(on-download-stop)
on-download-error=

希望在下载失败之后重试一次，能够实现断点续传，省去手动按重试的麻烦，请问应该怎么写sh脚本？

**Comment by P3TERX** [comment]
这个想法不错，不过实现起来并不容易，我个人时间和精力有限，暂时不会去研究这个。有想法自己动手建议去学习 Linux 基础知识和阅读 Aria2 文档。
