### ISSUE TITLE
请求写一个win下的move.bat，用于下载完成后移动文件并删除.aria2。

### ISSUE THREAD

**Issue by Dzzccbb** [P3TERX/aria2.conf#32]
因为不会在win下挂钩$1$2$3，直接执行on-download-complete="del "$3.aria2"不行，请求写一个move.sh作用的文件。

**Comment by P3TERX** [comment]
不懂批处理，这个就没办法帮到你了。话说 Windows 下那么多好的下载软件也没必要去折腾 Aria2
