### ISSUE TITLE
首先感谢付出，有几个问题请教一下。

### ISSUE THREAD

**Issue by yiiha33** [P3TERX/aria2.conf#38]
1. exclude-file=html|url|lnk|txt|jpg|png|nfo 关于排除选项机制，
注释是：在下载完成后。需要on-download-error=
去触发还是完成自动判断删除呢；其次，除了注释范例中的后缀名，这句命令支持自定义添加的后缀么？（比如我加了nfo）在测试的时候我下载了百度首页，index.html这个文件是会被上传，这里不知道是否单文件不进行判断，还我使用方式有问题或是代码失效。

2. 关于rclone配置
drive-name=gd       |       drive-name=gd
drive-dir=/temp      |       drive-dir=/home/gdrive/temp
左边为正确配置，以谷歌网盘为根目录；右边为挂载点。网上很多非整合脚本用的是挂载路径。建议您可用在注释中多提一嘴区别挂载点，让我等码盲不至于在此绕圈圈。

3. 建议安装包第一层只放aria2.conf、script.conf这两个文件或者其他文件隐藏（也许是我天真了）。从使用者角度而言，upload.sh我没可能看懂，仔细阅读github才帮助我找到了script。其他调用配置文件其实根本没必要看到，方便使用者和防止误操作都是很好的。

最后再次感谢一版又一版的改进和付出。

**Comment by P3TERX** [comment]
1. 不需要额外设置，去掉选项开头的`#`即可启用，可自定义后缀。
2. 感谢建议。
3. 如果是看的我的教程应该不会有这样的疑问，教程中只提及了修改`aria2.conf`、`script.conf`这两个文件，没有其它额外的操作。
