### ISSUE TITLE
Some shells don't have `command`  有些shell没有`command`命令

### ISSUE THREAD

**Issue by yaohappiness** [P3TERX/aria2.conf#40]
[tracker.sh#L108](https://github.com/P3TERX/aria2.conf/blob/master/tracker.sh#L108) uses `command`, but somes shell don't have it.  e.g.Busybox build in shell, ash. 

[tracker.sh#L108](https://github.com/P3TERX/aria2.conf/blob/master/tracker.sh#L108) 用了`command`命令，但是有些shell没有这个命令，比如Busybox内置的ash。

**Comment by P3TERX** [comment]
这是一个 bash 脚本。要么装 bash 去调用，要么自己修改去适配。
