### ISSUE TITLE
自定义下载路径，其中一个种子完成后触发上传，会上传同下载目录的其他未完成文件

### ISSUE THREAD

**Issue by nekojp** [P3TERX/aria2.conf#44]
使用flexget的rss订阅推送与自定义下载路径功能。
开启下载完成rclone上传。

同个订阅里的多个种子共用一个自定义下载目录，如“/root/downloads/电视剧第一季”。
其中一个种子下载完成触发上传脚本，上传脚本会尝试把“电视剧第一季”里面的都上传上去。

我禁用磁盘缓存+禁用rclone上传失败重试应该能解决大部分。文件变动的话就会上传失败达到不影响正在下载的文件效果。

题外话：被删除的未下载完成的文件，所对应的任务在文件被删除后仍继续下载，但下载完成后文件也没回来。（正常现象

**Comment by TheLonelinessOfHS** [comment]
+1 求修复

**Comment by P3TERX** [comment]
#56
