### ISSUE TITLE
可以添加自动上传脚本的并行数选择选项吗?

### ISSUE THREAD

**Issue by chuanshuozhongdegongzi** [P3TERX/aria2.conf#47]
如题，我的vps的cpu是3900X虚拟的，按理说性能不差了，可是当我下载一部电视剧时，包含几十个直链，通常下载速度远大于上传速度（世纪互联单个文件上传速度限制100Mbs）。于是就出现问题了，vps本地有多少文件，脚本就会生成多少个并行的rclone任务。cpu和内存在相当长的一段时间内都几乎处于满载状态。所以我想能不能给rclone的上传并行数加一个限制。

**Comment by P3TERX** [comment]
可以通过`rclone.env`文件去设置
https://github.com/P3TERX/aria2.conf/blob/8af2e31bf7f31e3cd62d4ec003904689673ab4af/rclone.env#L19
