### ISSUE TITLE
请教一下 dish-cache 这个选项的作用

### ISSUE THREAD

**Issue by lizhaode** [P3TERX/aria2.conf#49]
我看到 aria2 的文档中说这个选项可以配置下载文件时，先下载到内存中的大小

那么我配置这个 =512M  是不是就是说明下载一个好几个G大小的文件的时候，最多会占用内存512M

我是这么理解的，但是实际配置的时候发现内存占用很小

因为我想减少磁盘的读写，所以不知道我是不是对这个配置的理解有误

感谢

**Comment by P3TERX** [comment]
是`disk-cache`吧。这个值决定了上限，并不是一定会占满。实际占用要看你的网速和设备性能等其它因素。

**Comment by P3TERX** [comment]
补充一点，想进一步减少磁盘读写还需要调整`auto-save-interval`(任务进度保存间隔时间)这个选项的值

https://github.com/P3TERX/aria2.conf/blob/31e5ecbc292a32a067e974d372ccdb175680a4c7/aria2.conf#L67

**Comment by lizhaode** [comment]
多谢，这个配置我看说明是保存 .aria2 这个后缀名的文件
这个会影响什么吗？因为我看这个文件就几K大小

**Comment by P3TERX** [comment]
影响读写次数和缓存刷新频率

**Comment by lizhaode** [comment]
了解了，多谢
