### ISSUE TITLE
support exclude-file-regex

### ISSUE THREAD

**Issue by hereisderek** [P3TERX/aria2.conf#52]
之前在 [这里](https://github.com/P3TERX/Aria2-Pro-Docker/issues/38)提出的 现在移到这里来

添加原本的正则表达式支持 

`exclude-file-regex` & `include-file-regex`

主要用于自动删除类似于 

![image](https://user-images.githubusercontent.com/839795/114704667-f9f3af80-9d7a-11eb-827e-e78f021b658a.png)

` _____padding_file_236_如果您看到此文件，请升级到BitComet(比特彗星)0.85或以上版本____  ` 

最好能支持多个正则表达式的匹配

**Comment by P3TERX** [comment]
感谢！不过你那个 PR 有点混乱，还带了自己改的配置文件。不过好在我用重写历史给救回来了。
