### ISSUE TITLE
能否出一个下载完成发出通知的脚本

### ISSUE THREAD

**Issue by iso-lib** [P3TERX/aria2.conf#60]
带上文件名,大小等信息

通知到邮件,server酱,或者TG,或者企业微信

随便哪一个都行

唉,自己不会代码,,流下不学无术悔恨的泪水.

**Comment by lalasou** [comment]
我用的docker 就是大佬 aria2-pro那个版本

ok  设置好了 
修改script/clean.sh
前面添加
filename=$(basename $3)
curl https://api.day.app/xxxxxxxx/下载完成/$filename


就行了
clean.sh 有3个参数传进来 第三个是下载文件路径加文件名结构

但是不知道怎么排除种子文件下载
要不然种子下载好会通知一次  文件现在好又通知一次

**Comment by iso-lib** [comment]
> 我用的docker 就是大佬 aria2-pro那个版本
> 
> ok 设置好了 修改script/clean.sh 前面添加 filename=$(basename $3) curl [https://api.day.app/xxxxxxxx/下载完成/$filename](https://api.day.app/xxxxxxxx/%E4%B8%8B%E8%BD%BD%E5%AE%8C%E6%88%90/$filename)
> 
> 就行了 clean.sh 有3个参数传进来 第三个是下载文件路径加文件名结构
> 
> 但是不知道怎么排除种子文件下载 要不然种子下载好会通知一次 文件现在好又通知一次

原来如此,,,种子文件可以用if判断 ,,,文件名含有.torrent就不执行curl
