### ISSUE TITLE
请问如何在命令行下使用 aria2c 下载

### ISSUE THREAD

**Issue by BlueHeart0621** [P3TERX/aria2.conf#61]
你好，我想请教一个问题。
我在我的远程服务器上成功配置了 aria2，但我尝试在命令行上使用 `aria2c` 指定 url 下载发现，aria2c 一直作为守护进程开着，并没有下载我给定的 url 地址。请问没有图形化界面要如何使用配置后的 aria2 呢。

谢谢！

**Comment by qinheJ** [comment]
> 你好，我想请教一个问题。 我在我的远程服务器上成功配置了 aria2，但我尝试在命令行上使用 `aria2c` 指定 url 下载发现，aria2c 一直作为守护进程开着，并没有下载我给定的 url 地址。请问没有图形化界面要如何使用配置后的 aria2 呢。
> 
> 谢谢！

我发现把有关session的配置去掉才可以用命令行下载
